	
py:
	python bundle_lister.py 
	cp bundles.html.txt ../../introduction
	rm -rf cloned_repo/*
	rm bundles.html.txt
	@echo "Python script finished succesfully!"
	@echo "Next run make html. Then run make publish."

