
py:
	python bundle_lister/bundle_lister.py
	cp bundle_lister/bundles.html.txt ../../clear-linux/reference/bundles
	rm -rf cloned_repo/*
	rm bundle_lister/bundles.html.txt
	@echo "Python script finished successfully!"


